# Generated by Django 3.0 on 2025-07-23 12:38

from django.db import migrations


def copy_profiles_data(apps, schema_editor):
    Profile = apps.get_model('profiles', 'Profile')
    cursor = schema_editor.connection.cursor()

    cursor.execute("SELECT id, user_id, favorite_city FROM oc_lettings_site_profile")
    for row in cursor.fetchall():
        Profile.objects.create(
            id=row[0],
            user_id=row[1],
            favorite_city=row[2]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        # migrations.RunPython(copy_profiles_data),
    ]

