# Generated by Django 3.0 on 2025-07-23 12:36
from django.db import migrations



def copy_lettings_data(apps, schema_editor):
    Address = apps.get_model('lettings', 'Address')
    Letting = apps.get_model('lettings', 'Letting')
    cursor = schema_editor.connection.cursor()

    # Copier les adresses
    cursor.execute("SELECT id, number, street, city, state, zip_code, country_iso_code FROM oc_lettings_site_address")
    for row in cursor.fetchall():
        Address.objects.create(
            id=row[0], number=row[1], street=row[2], city=row[3],
            state=row[4], zip_code=row[5], country_iso_code=row[6]
        )

    # Copie les lettings
    cursor.execute("SELECT id, title, address_id FROM oc_lettings_site_letting")
    for row in cursor.fetchall():
        Letting.objects.create(
            id=row[0], title=row[1], address_id=row[2]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),  
    ]

    operations = [
        migrations.RunPython(copy_lettings_data),
    ]
